### ISSUE TITLE
explain results of getpapers

### ISSUE THREAD

**Issue by skasberger** [ContentMine/workshop-resources#24]
after the first call of getpapers, in which results get produced, we should explain the results. where are the fulltext files, why are the missing? is it okay, that something is missing? what needs to be inside the CProject? 
- results.json
- fulltext.html
- fulltext.pdf
- fulltext.xml
- fulltext_html_urls.txt: urls wozu ein fulltext gefunden wurde

**Comment by skasberger** [comment]
are the outcomes always the same regarding getpapers command? if not, explain the parameters behind.

**Comment by skasberger** [comment]
also eupmc_results.json etc.

**Comment by chreman** [comment]
from [#52](https://github.com/ContentMine/workshop-resources/issues/52):
- What is the .json file exactly (results)?
