### ISSUE TITLE
getpaper: describe better the causes for flags

### ISSUE THREAD

**Issue by skasberger** [ContentMine/workshop-resources#27]
- why to use them?
- what is the cause for the flag? the data source, the software?

try to harmonize the flags and functions we work with. => sw development

**Comment by chreman** [comment]
from [#52](https://github.com/ContentMine/workshop-resources/issues/52):
- Can we restrict the number of items to download?
- Can we use multiple search term Boolean queries to narrow results at getpapers stage?
