### ISSUE TITLE
better description of quickscrape and getpapers

### ISSUE THREAD

**Issue by skasberger** [ContentMine/workshop-resources#28]
describe better what quickscrape does in the introduction section.

we need a better entry point for getpapers and quickscrape
- quickscrape is for html based publishing plattforms like plos, elife, etc
- getpapers is for api based publication retrieval
- a diagramm in the README.md file should help to better understand this. should also show the processes before and after the usage of the software packages
- use use-cases which clearly seperates from each other: EUPMC for getpapers and some html which is not stored on EUPMC for quickscrape

**Comment by chreman** [comment]
closed by https://github.com/ContentMine/workshop-resources/commit/846f88f0a458df95d65301a30265bb8c57020313
