### ISSUE TITLE
Merging general workflow and check lists?

### ISSUE THREAD

**Issue by jcmolloy** [ContentMine/workshop-resources#44]
Working through them, it's quite confusing to keep swapping between the pages - would it be possible to have everything together?

**Comment by chreman** [comment]
probably yes, I need to rethink the structure and presentation a bit, but if it is better for facilitators then we should do it.

**Comment by jcmolloy** [comment]
Thanks! Peter and I are working through everything and commenting/making notes here https://docs.google.com/document/d/1XVj38r1xE3wiAVNobcmgrsmZYJ5o-2W5f-a6Sl1Zz1o/edit
