### ISSUE TITLE
Alpha documentation for Canary

### ISSUE THREAD

**Issue by petermr** [ContentMine/workshop-resources#48]
Create a schematic , with links,  of the currently working components of canary for (a) tutorial presenters (b) self-learners 
Also annotate any Canary training module with indication that this is alpha

**Comment by markmacgillivray** [comment]
https://docs.google.com/drawings/d/1mQZBw7nmg2IrooN9ZmQgfvzCmNRu8zOuCm-tKLfWlWM/edit

**Comment by chreman** [comment]
closed since functionality moved to API
