### ISSUE TITLE
broken links on Virtualbox workshop page

### ISSUE THREAD

**Issue by jibe-b** [ContentMine/workshop-resources#59]
Hi, there are at least two broken links on https://github.com/ContentMine/workshop-resources/blob/master/software-tutorials/vms/README.md which are:
- https://contentmining.files.wordpress.com/static/contentmine-VM.ova
- https://github.com/ContentMine/workshop-resources/blob/master/software-tutorials/shell/shell-tutorial.md

and not pointing to the expected pages.

Best regards,

**Comment by chreman** [comment]
Thank you @jibe-b, a few links have been fixed and an updated version of the VM is being uploaded and should be available from Saturday on (May 21st 2016), I'll update the link to the new VM when it is ready.

**Comment by jibe-b** [comment]
thanks @chreman!
