### ISSUE TITLE
norma fails if additional directories are in the project dir without a fulltext.xml file

### ISSUE THREAD

**Issue by cameronneylon** [ContentMine/workshop-resources#8]
Repeatable error. If a set of xml files is collected using getpapers and then further directories (or possibly files) are added to that project directory then normal will fail as follows:

```
norma -q test_eupmc_neylon/ -i fulltext.xml -o scholarly.html --transform nlm2html
[...]
154  [main] ERROR org.xmlcml.norma.NormaTransformer  - no transforms given/parsed
```

Starting over with a fresh getpapers -x into a new directory, followed by norma works as expected:

```
>> rm -rf test_eupmc_neylon/
>> getpapers -q 'AUTH:"Cameron Neylon"' -o neylon-xmls -x
[...]
>> norma -q neylon-xmls -i fulltext.xml -o scholarly.html --transform nlm2html
[...]
>> ls neylon-xmls/PMC3720848/
fulltext.xml  scholarly.html
```

**Comment by chreman** [comment]
Are the directories empty?

If yes, this is related to a [getpapers issue](https://github.com/ContentMine/getpapers/issues/45), and the behaviour is going to be fixed once the definite structure of ctree is settled. Meanwhile I added a [small hack](https://github.com/ContentMine/workshop-resources/blob/master/software-tutorials/norma/norma-tutorial.md#troubleshooting) how to work around this issue between getpapers and norma:

``` bash
cd test_eupmc_neylon
find -empty -delete
cd ..
```

**Comment by cameronneylon** [comment]
Yes, that was the problem. quickscrape timing out on article recovery also leads to empty directories which can also cause a problem apparently. Question - there are some bugs that relate to interactions between ContentMine components (we had issues yesterday with norma outputting in a form ami didn’t understand). How should those be raised?

Also would be good to get checkpointed VMs and/or containers that are known to work along the existing tool chain. 

Cameron Neyloncn@cameronneylon.net - http://cameronneylon.net

@cameronneylon - http://orcid.org/0000-0002-0068-716X

**Comment by chreman** [comment]
Your suggestion of creating working containers for each step within the VM is going to be implemented in the next version, thank you for that!
